### ISSUE TITLE
Add FAQ content

### ISSUE THREAD

**Issue by MariusLang** [inf-lab-dev/advent#3]
The website contains a **FAQ section**. This section needs to be filled up with content.

## General
- [x] I'm feeling overwhelmed by all the tasks I can do for inf-einf-b. What to do? -> Just do tasks at inf.zone
- [x] What's the benefit participating here?
- [x] Can we work on the tasks in groups?

## Submission
- [x] How to submit a task?
- [x] Whats included in my submission token?
- [x] Why do I have to submit a token?
- [x] My token is different each time I generate it, is that normal?
- [x] Why do I have to confirm, that I understood the relevance of the material?

## Tasks
- [x] I cannot solve a task, can I still submit a token?
- [x] I could not solve last week's task, can I still participate in this week?
- [x] Can I also use programming languages other than C?
    - **Answer:** Yes, but tasks are designed for C, you can however also use various languages, if you need assistance, we suggest to use languages we understand, like C++, C#, Lua, Java/Scala/Kotlin/Groovy, Python, Ruby, Haskell, Rust, Js/Ts/Coffee Script, PHP, Dart, Swift, Go, Julia, Bash (and other shells like PowerShell or Batch), Elixir, Pascal, Lisp/Scheme/Racket, Zig  _this currently only includes languages @Kuschel-Swein is comfortable with, expand the list with your languages!_
 - [x] Will the eplilogue of a task get published at some time?
      - **Answer:** Yes, once a new task is published the prior task will be made public and thus the epiloge may be viewed without the _password_. However, you cannot generate a token from then on.
- [x] When are the new tasks published?
     - **Answer:** New tasks will be published every advent sunday in the morning at `10:00`
